version: '2'
services:
  bugtracker-app:
    image: bugtracker
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bugtracker-postgresql:5432/bugTracker
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  bugtracker-postgresql:
    extends:
      file: postgresql.yml
      service: bugtracker-postgresql
